platform :"ios", "8.0"
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'RxSegue_Example' do
  pod "RxSegue", :path => "../"
end

target 'RxSegue_Tests' do
  pod "RxSegue", :path => "../"

  pod 'Quick'
  pod 'Nimble'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'RxSwift' || target.name == 'RxCocoa'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = ['$(inherited)', '-D', 'TRACE_RESOURCES']
                end
            end
        end
    end
end
